<?php

/**
 * Provide a admin area view for the plugin
 *
 * This file is used to markup the admin-facing aspects of the plugin.
 *
 * @link       https://dac.ds.unipi.gr/policycloud-eu/
 * @since      1.0.0
 *
 * @package    PolicyCloud_Marketplace
 * @subpackage PolicyCloud_Marketplace/admin/partials
 */

function render_settings_page()
{
?>
    <h2>PolicyCLOUD Data Marketplace Settings</h2>
    <p>This is the options page for the PolicyCLOUD Data Marketplace API.</p>
    <form action="options.php" method="post">
        <?php
        settings_fields('policycloud_marketplace_plugin_settings');
        do_settings_sections('policycloud_marketplace_plugin');
        ?>
        <br />
        <input type="submit" name="submit" class="button button-primary" value="<?php esc_attr_e('Save'); ?>" />
    </form>
<?php
}

function policycloud_marketplace_plugin_section_one()
{
    echo '<p>Insert your credentials for the Marketplace API.</p>';
}

function policycloud_marketplace_plugin_host()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
?>
    <input type="text" name="policycloud_marketplace_plugin_settings[marketplace_host]" value="<?php echo ((!empty($options['marketplace_host'])) ? $options['marketplace_host'] : '') ?>" />
    <p>The Marketplace server address endpoint.</p>
<?php
}

function policycloud_marketplace_plugin_api_access_token()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
?>
    <input type="text" name="policycloud_marketplace_plugin_settings[api_access_token]" value="<?php echo ((!empty($options['api_access_token'])) ? $options['api_access_token'] : '') ?>" />
    <p>The Marketplace server address endpoint.</p>
<?php
}

function policycloud_marketplace_plugin_jwt_key()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
?>
    <input type="text" name="policycloud_marketplace_plugin_settings[jwt_key]" value="<?php echo ((!empty($options['jwt_key'])) ? $options['jwt_key'] : '') ?>" />
    <p>The Marketplace server token decoding key.</p>
<?php
}

function policycloud_marketplace_plugin_encryption_key()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
?>
    <input type="text" id="policycloud-marketplace-encryption-key" name="policycloud_marketplace_plugin_settings[encryption_key]" value="<?php echo ((!empty($options['encryption_key'])) ? $options['encryption_key'] : '') ?>" />
    <button id="policycloud-marketplace-generate-key" class="button button-primary">Generate</button>
    <p>The Marketplace authorization token encryption key. This key must be generated by you and kept security confidential.</p>
<?php
}

function policycloud_marketplace_plugin_section_two()
{
    echo '<p>Select your preferred operating settings.</p>';
}

function policycloud_marketplace_plugin_login_page_selector()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
    $pages = get_pages([
        'post_status' => 'publish'
    ]);
?>
    <select name="policycloud_marketplace_plugin_settings[login_page]">
        <option value="" selected>-</option>
        <?php
        foreach ($pages as $page) {
            echo '<option value="' . $page->ID . '" ' . (($options['login_page'] == $page->ID) ? 'selected' : '') . '>' . $page->post_title . '</option>';
        }
        ?>
    </select>
    <p>Select the log in page where the "Log In" menu item should redirect.</p>
<?php
}

function policycloud_marketplace_plugin_registration_page_selector()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
    $pages = get_pages([
        'post_status' => 'publish'
    ]);
?>
    <select name="policycloud_marketplace_plugin_settings[registration_page]">
        <option value="" selected>-</option>
        <?php
        foreach ($pages as $page) {
            echo '<option value="' . ($page->ID) . '" ' . ($options['registration_page'] == ($page->ID) ? 'selected' : '') . '>' . $page->post_title . '</option>';
        }
        ?>
    </select>
    <p>Select the registration page where the "Register" menu item should redirect.</p>
<?php
}


function policycloud_marketplace_plugin_account_page_selector()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
    $pages = get_pages([
        'post_status' => 'publish'
    ]);
?>
    <select name="policycloud_marketplace_plugin_settings[account_page]">
        <option value="" selected>-</option>
        <?php
        foreach ($pages as $page) {
            echo '<option value="' . ($page->ID) . '" ' . ($options['account_page'] == ($page->ID) ? 'selected' : '') . '>' . $page->post_title . '</option>';
        }
        ?>
    </select>
    <p>Select the account page where the "My Account" menu item should redirect.</p>
<?php
}

function policycloud_marketplace_plugin_menu_selector()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
    $menus = get_registered_nav_menus();
?>
    <select name="policycloud_marketplace_plugin_settings[selected_menu]">
        <option value="" selected>-</option>
        <?php
        foreach ($menus as $location => $description) {
            echo '<option value="' . $location . '" ' . ($options['selected_menu'] == $location ? 'selected' : '') . '>' . $description . '</option>';
        }
        ?>
    </select>
    <p>Select the menu where the Log In and Log Out buttons to appear.</p>
<?php
}

function policycloud_marketplace_plugin_section_three()
{
    echo '<p>Select your preferred operating settings.</p>';
}


function policycloud_marketplace_plugin_password_reset_page_selector()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
    $pages = get_pages([
        'post_status' => 'publish'
    ]);
?>
    <select name="policycloud_marketplace_plugin_settings[password_reset_page]">
        <option value="" selected>-</option>
        <?php
        foreach ($pages as $page) {
            echo '<option value="' . ($page->ID) . '" ' . ($options['password_reset_page'] == ($page->ID) ? 'selected' : '') . '>' . $page->post_title . '</option>';
        }
        ?>
    </select>
    <p>Select the page where you've inserted the <em>[policycloud-marketplace-user-password-reset]</em> shortcode.</p>
<?php
}

function policycloud_marketplace_plugin_tos_url()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
?>
    <input type="text" name="policycloud_marketplace_plugin_settings[tos_url]" value="<?php echo ((!empty($options['tos_url'])) ? $options['tos_url'] : '') ?>" />
    <p>The Terms of Use page URL for the registration process.</p>
<?php
}

function policycloud_marketplace_plugin_description_page_selector()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
    $pages = get_pages([
        'post_status' => 'publish'
    ]);
?>
    <select name="policycloud_marketplace_plugin_settings[description_page]">
        <option value="" selected>-</option>
        <?php
        foreach ($pages as $page) {
            echo '<option value="' . ($page->ID) . '" ' . ($options['description_page'] == ($page->ID) ? 'selected' : '') . '>' . $page->post_title . '</option>';
        }
        ?>
    </select>
    <p>Select the page where you've inserted the <em>[policycloud-marketplace-description]</em> shortcode.</p>
<?php
}

function policycloud_marketplace_plugin_archive_page_selector()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
    $pages = get_pages([
        'post_status' => 'publish'
    ]);
?>
    <select name="policycloud_marketplace_plugin_settings[archive_page]">
        <option value="" selected>-</option>
        <?php
        foreach ($pages as $page) {
            echo '<option value="' . ($page->ID) . '" ' . ($options['archive_page'] == ($page->ID) ? 'selected' : '') . '>' . $page->post_title . '</option>';
        }
        ?>
    </select>
    <p>Select the page where you've inserted the <em>[.policycloud-marketplace.descriptions.archive]</em> shortcode.</p>
<?php
}

function policycloud_marketplace_plugin_upload_page_selector()
{
    $options = get_option('policycloud_marketplace_plugin_settings');
    $pages = get_pages([
        'post_status' => 'publish'
    ]);
?>
    <select name="policycloud_marketplace_plugin_settings[upload_page]">
        <option value="" selected>-</option>
        <?php
        foreach ($pages as $page) {
            echo '<option value="' . ($page->ID) . '" ' . ($options['upload_page'] == ($page->ID) ? 'selected' : '') . '>' . $page->post_title . '</option>';
        }
        ?>
    </select>
    <p>Select the page where you've inserted the <em>[policycloud-marketplace-description-creation]</em> shortcode.</p>
<?php
}
